# Hi, I'm the Jail++ configuration file.
# And I'm a comment! I start with a "#", which means I can give you tips on how to configure Jail++.

# Here you can configure your database. You can use H2 embedded or MySQL!
# If you don't have a MySQL database, I would stick with the default settings (h2), which uses an embedded database.
database:
  # Choose 'h2', 'mysql', or 'file' (h2 is recommended over file due to better performance, security, and stability)
  driver: h2
  # Not used for h2 or file. The hostname of the MySQL server.
  host: localhost
  # Not used for h2 or file. If you don't know what your port is for mysql, it's probably 3306.
  port: 3306
  # Not used for h2 or file. The user Jail++ will use to connect to the database.
  user: jailplusplus
  # Not used for h2 or file. The password of the user set above.
  password: example
  # Not used for h2 or file. The name of the mysql database to use.
  database: minecraft
  # Not used for file. You can leave this as default if you don't know what it means.
  prefix: jpp_

# Choose the item ID that you want the wand to be (blaze rod by default)
wand-id: 369

# Update stuff
update:
  # Update Stream can be: Release, Beta, Alpha, Dev
  stream: release

# The configuration is done! Don't touch anything in the file or bad things may happen :'(
seriously-don't-touch-this: 1