# Hi, I'm the Jail++ configuration file.
# And I'm a comment! I start with a "#", which means I can give you tips on how to configure Jail++.

# Here you can configure your database. You can use H2 embedded or MySQL!
# If you don't have a MySQL database, I would stick with the default settings (h2), which uses an embedded database.
database:
  # Choose 'h2' or 'mysql'

  # h2 is an embedded database that is fast, secure, and stable.
  # you don't have to do anything to use it, just set the driver to 'h2'

  # mysql is a database server that is also fast, secure, and stable.
  # with mysql it's easier to access plugin data from other sources, but you need an external server to use it.
  driver: h2
  # Not used for h2. The hostname of the MySQL server.
  host: localhost
  # Not used for h2. If you don't know what your port is for mysql, it's probably 3306.
  port: 3306
  # Not used for h2. The user Jail++ will use to connect to the database.
  user: jailplusplus
  # Not used for h2. The password of the user set above.
  password: example
  # Not used for h2. The name of the mysql database to use.
  database: minecraft
  # You can leave this as default if you don't know what it means.
  prefix: jpp_

# Choose the item ID that you want the wand to be (blaze rod by default)
wand-id: 369

# Update stuff
update:
  # Update Stream can be: Release, Beta, Alpha, Dev
  stream: release

# The configuration is done! Don't touch anything further in the file or bad things may happen :'(
seriously-don't-touch-this: 1