name: JailPlusPlus
version: 1.0a b1
description: An advanced Jail plugin for Bukkit servers.
authors: [goldblattster, tyzoid, yoshigenius]
main: tk.ultimatedev.jailplusplus.JailPlugin
commands:
  jpp:
    permission: jpp.main
    usage: /jpp help
    description: Main JailPlusPlus command.
    aliases: [jailplusplus]
  jail:
    permission: jpp.main
    usage: /jail help
    description: Jailing command.
permissions:
  jpp.*:
    description: Gives access to all JailPlusPlus abilities
    default: op
    children:
      jpp.wand: true
  jpp.wand:
    description: Use the JailPlusPlus wand